### ISSUE TITLE
Search Yeilded No Results while the records exists

### ISSUE THREAD

**Issue by PseudoAj** [wvulibraries/rockefeller-css#10]
PFA I am searching for the term `farmers` using `addr1` and search returned:

> Search Yeilded No Results

While the records exists in the table. Search needs to be fixed. PFA the screenshots:

![issue-2-2](https://user-images.githubusercontent.com/3308051/27451169-11e830ac-5743-11e7-959f-d35326e67a90.png)
![issue-2-1](https://user-images.githubusercontent.com/3308051/27451168-11e63c98-5743-11e7-9823-0b2a8d2c42c5.png)

**Comment by trmccormick** [comment]
Rewrote search no uses a separate search package. We do not need to pick the field. Testing searching for farmers and it worked correctly.
