### ISSUE TITLE
Search Tests:  

### ISSUE THREAD

**Issue by ddavisgraphics** [wvulibraries/rockefeller-css#11]
Tracy and Ajay thus far have been testing searching tools and implementations, in order to choose which one is best we need to do some benchmark testing. 

I think some of the basic areas we should look at for testing are 
-- Return the Results (Database / Server) 
-- Process the Results (Server) 
-- Render the View (Server / Client ) 
-- Total 

The idea is that we can find out which one is the fastest in the four areas and we can decide which ways we can improve that speed.  Example if the render the view aspect is the slowest part, truncating to the first 25 results or using pagination to control the views.

**Comment by ddavisgraphics** [comment]
I'm also thinking that TDD may help here, if we write the tests first we can give exact standards for tasks that the search has to be able to accomplish. It will help to keep it on point, while also getting the code tested.

**Comment by ddavisgraphics** [comment]
Another potential solution you may want to look into is creating a search index column inside of your table.  There are a couple of ways you could do this, by storing it in a single column in your table so that you don't have to search each column.  This would eliminate the sheer number of columns that your searching on and may help the results come back faster.

**Comment by trmccormick** [comment]
fulltext search has been implemented.
