### ISSUE TITLE
Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by PseudoAj** [wvulibraries/rockefeller-css#12]
# The Problem

Running into following error while importing the `400 mb` correspondence data:

> Maximum execution time of 30 seconds exceeded  

# Process followed to recreate the error

1. Created table
![ccdt-bug-1](https://user-images.githubusercontent.com/3308051/27780613-d3b2ec84-5f7e-11e7-9f20-c54c8376ac83.png)

2. Added schema
![ccdt-bug-2](https://user-images.githubusercontent.com/3308051/27780620-dff6c9ca-5f7e-11e7-806f-8c3fbde2adc8.png)

3. Started import
![ccdt-bug-3](https://user-images.githubusercontent.com/3308051/27780626-ebdcd810-5f7e-11e7-8c3b-e771fd3db65b.png)

4. Encountered error
![ccdt-bug-4](https://user-images.githubusercontent.com/3308051/27780637-f8942f36-5f7e-11e7-9033-aec9b0ea2a20.png)

# Solution

Although there is a fix by simply adding following as suggested [here](https://stackoverflow.com/questions/5164930/fatal-error-maximum-execution-time-of-30-seconds-exceeded):

```php
ini_set('max_execution_time', 300); //300 seconds = 5 minutes
```

But I believe this could because of the bulk import logic and needs to be verified.

**Comment by trmccormick** [comment]
did you try to manually put the file into the flatfiles folder instead of trying to use the upload. That is what I needed to do to get my file to import.

**Comment by PseudoAj** [comment]
@trmccormick Yes, I have the file uploaded successfully. It is in the `Storage` directory.

**Comment by trmccormick** [comment]
could you spawn another process to handle the import. that way you shouldn't need to worry about the timeout issue.

**Comment by PseudoAj** [comment]
@trmccormick We need to implement a [laravel queue](https://laravel.com/docs/5.3/queues) for this. Right now I am fixing it by handling it in worker() method. Will revisit and streamline this problem.

**Comment by trmccormick** [comment]
Implemented the laravel queue for importing the flat files tested and we no longer have the browser timeout issue. Still need to check into the production setup for docker to ensure the queue manager stays running.
