### ISSUE TITLE
CSS redering issue while displaying cards

### ISSUE THREAD

**Issue by PseudoAj** [wvulibraries/rockefeller-css#13]
`col-md-4` rendering grid unevenly as displayed in the following picture. Works fine for the similar records.
![css-bug](https://user-images.githubusercontent.com/3308051/27846455-5090c6b8-60ec-11e7-8a4a-bd46c01f3b56.png)

**Comment by trmccormick** [comment]
Is their a way we can limit text in the card to prevent overflow?

**Comment by trmccormick** [comment]
Was able to adjust the grid layout in the specific view. Now it will switch to 2 columns instead of trying to wrap the text.
