### ISSUE TITLE
Attached Document Viewer:  

### ISSUE THREAD

**Issue by ddavisgraphics** [wvulibraries/rockefeller-css#16]
We need to have a way to link and view documents that are attached to the various records.

If it is a text file, parse all the text in the file to an HTML page, while doing so we need to filter out any special numbers (social security), look into some pattern matching regex for social security numbers and turn them into astricts to appear, *** - ** - ****, like this.

**Comment by trmccormick** [comment]
this is working correctly for now in the fileViewer branch. the view still needs some css work I have a basic page that we are doing just a var_dump on the text.

**Comment by ddavisgraphics** [comment]
Data needs to be formatted and extracted nicely.  Don't just var dump the text.  Work on extracting the parts and pieces that we need or want to use in an elegant manner.

**Comment by trmccormick** [comment]
created view that will format the extracted text. Also allows the user to click back to the original record.
