### ISSUE TITLE
SQLSTATE[22001]: String data, right truncated: 1406 Data too long

### ISSUE THREAD

**Issue by trmccormick** [wvulibraries/rockefeller-css#4]
When trying to import we used "Select from directory" and imported the large file archiving_correspondence.dat we get the error above. All fields were set to String and Size was set to Big.

**Comment by trmccormick** [comment]
QueryException in Connection.php line 770:
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'in_text' at row 1 (SQL: insert into `import1` (`prefix`, `first`, `middle`, `last`, `suffix`, `appellation`, `title`, `org`, `addr1`, `addr2`, `addr3`, `addr4`, `city`, `state`, `zip`, `country`, `in_id`, `in_type`, `in_method`, `in_date`, `in_topic`, `in_text`, `in_document_name`, `in_fillin`, `out_id`, `out_type`, `out_method`, `out_date`, `out_topic`, `out_text`, `out_document_name`, `out_fillin`) values

**Comment by trmccormick** [comment]
Continued testing

SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\x92t lik...' for column 'in_text' at row 1 (SQL: insert into `import8` (`prefix`, `first`, `middle`, `last`, `suffix`, `appellation`, `title`, `org`, `addr1`, `addr2`, `addr3`, `addr4`, `city`, `state`, `zip`, `country`, `in_id`, `in_type`, `in_method`, `in_date`, `in_topic`, `in_text`, `in_document_name`, `in_fillin`, `out_id`, `out_type`, `out_method`, `out_date`, `out_topic`, `out_text`, `out_document_name`, `out_fillin`) values

**Comment by PseudoAj** [comment]
Resolved. Closing the issue.
