### ISSUE TITLE
Accessibility A and AA Errors:  

### ISSUE THREAD

**Issue by ddavisgraphics** [wvulibraries/rockefeller-css#8]
The following are some accessibility errors I've noticed.  These are **super** important since its government documents going into a digital collection from a state agency.

- Markup must use the proper HTML tags or include aria roles and labels, this is to ensure logical way finding for assistive technology.  
- All input fields must have a label that describes what goes into the input (select, input, checkboxes, etc) 
- Checkboxes or Radio buttons must be grouped using the appropriate aria-role.  
- Hidden content or toggles must have the appropriate aria roles that change when the item is toggled.  
- A skip to content tag should be placed at the top of the page and be the first focusable link.  This link does not need to be visible but needs to be reached by using the Tab key.  
- All links need to be visually distinguished by more than just color.  
- The Proper heading structure must be followed, first heading is an H1, second is h2, h3, etc.  If you need to change them visually do it with css and making a class for those elements to be changed.

**Comment by ddavisgraphics** [comment]
http://www.508checker.com/

**Comment by ddavisgraphics** [comment]
https://github.com/accesslint/accesslint.js

**Comment by trmccormick** [comment]
Used siteImpove and WAVE plugin to check for proper aria formatting.
