### ISSUE TITLE
Label misplaced

### ISSUE THREAD

**Issue by PseudoAj** [wvulibraries/rockefeller-css#9]
![issue-1](https://user-images.githubusercontent.com/3308051/27450491-bc86bbbc-5740-11e7-8223-de722a8923c6.png)

PFA I believe label should be for the header not the individual fields.

**Comment by ddavisgraphics** [comment]
Accessibility constraint is that all input fields must have a label associated with that field, so while the label at the top may suffice, we would have to run it through web aim or create another example that we can run through an accessibility scanner first.  So I'm not sure, but you might be right.

**Comment by trmccormick** [comment]
removed this label so it is not properly formatted.
